server:
  port: 8080

spring:
  mvc:
    hiddenmethod:
      filter:
       enabled: true
  properties:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: testtest
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

